version: 2

jobs:
  build:
    working_directory: ~/open-controls
    docker:
      - image: continuumio/anaconda3
    steps:
      - run: apt-get -y install build-essential
      - checkout
      - run: python3 setup.py install
      - run: pytest
      - run: pytest --nbval-lax examples/*.ipynb --sanitize-with examples/notebook-sanitize.cfg
      - run: pylint qctrlopencontrols --rcfile=.pylintrc
      - run: pylint tests --rcfile=.pylintrc