version: 2.1

orbs:
  q-ctrl: q-ctrl/python@dev:0.1.2

workflows:
  version: 2

  "PyPI Project":
    jobs:
      - q-ctrl/pytest_python_36_test:
          name: pytest 3.6 (Production)
          context: q-ctrl-api-production
          filters:
            branches:
              only: 
                - master
            tags:
              only: /^v?\d+(\.\d+){1,2}$/
      - q-ctrl/pytest_python_37_test:
          name: pytest 3.7 (Production)
          context: q-ctrl-api-production
          filters:
            branches:
              only: 
                - master       
            tags:
              only: /^v?\d+(\.\d+){1,2}$/
      - q-ctrl/build_and_publish_internally:
          name: Build & Publish Internally
          context: q-ctrl-api-development
          filters:
            branches:
              only: 
                - master
            tags:
              only: /^v?\d+(\.\d+){1,2}$/              
      - q-ctrl/publish_publicly:
          context: q-ctrl-api-production
            - Build & Publish Internally
          filters:
            tags:
              only: /^v?\d+(\.\d+){1,2}$/