version: 2.1

orbs:
  q-ctrl: q-ctrl/python@dev:0.1.1

workflows:
  version: 2

  "PyPi Project":
    jobs:
      - q-ctrl/pytest_python_36_open:
          context: q-ctrl-api-development      
          filters:
            tags:  # Tag filter required because the release job has a tag filter
              only: /.*/
      - q-ctrl/open_build_and_publish_internally:
          context: q-ctrl-api-development
          filters:
            branches:
              only: 
                - master
            tags:  # Tag filter required because the release job has a tag filter
              only: /.*/                
      - q-ctrl/publish_publicly:
          context: q-ctrl-api-production
          requires:
            - q-ctrl/pytest_python_36_open          
            - q-ctrl/open_build_and_publish_internally
          filters:
            branches:
              only: 
                - master
            tags:
              only: /^v?\d+(\.\d+){1,2}$/
